"""Generate the compact conformance table from checked-in evidence.

Reads the normalized reports in ``reports/``, the run index in
``runs/index.json``, and the frozen rubric, then writes
``conformance.md`` next to this script. The output is deterministic:
the same evidence always produces the same bytes, and the replay tests
regenerate it to prove nothing drifted.

The table claims only what the evidence shows: the frozen handoff, the
three reference consumers with every check status visible (including
honest `unavailable` layers), and the cross-Agent run record status.
Artistic taste never appears here (plan section 13.3).

Usage:

    python evaluations/agent-interoperability/generate_conformance.py

Exit codes: 0 written, 1 evidence missing or inconsistent.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

EVAL_DIR = Path(__file__).resolve().parent
REPORTS_DIR = EVAL_DIR / "reports"
RUNS_INDEX_PATH = EVAL_DIR / "runs" / "index.json"
RUBRIC_PATH = EVAL_DIR / "rubric.json"
OUTPUT_PATH = EVAL_DIR / "conformance.md"

CONSUMER_REPORTS = (
    ("canvas-particles", "vanilla"),
    ("threejs-geometry", "three"),
    ("remotion-composition", "remotion"),
)
CHECK_ORDER = ("declaration", "handoff", "node-probe", "static", "browser", "offline", "visual-snapshot")
REQUIRED_AGENTS_FOR_CLAIM = 2


def _required_summary(checks: list[dict]) -> str:
    required = [check for check in checks if check["required"]]
    passed = sum(1 for check in required if check["status"] == "passed")
    return f"{passed}/{len(required)}"


def _status_cell(status: str) -> str:
    return f"`{status}`"


def build_markdown() -> str:
    lines: list[str] = []
    lines.append("# BeatScope v0.9 conformance evidence")
    lines.append("")
    lines.append(
        "Generated by `evaluations/agent-interoperability/generate_conformance.py` from the "
        "checked-in evidence; do not edit by hand. Every status below is the frozen validator's "
        "own verdict, including honest `unavailable` layers."
    )
    lines.append("")

    handoff = json.loads((REPORTS_DIR / "handoff-fixture.json").read_text(encoding="utf-8"))
    lines.append("## Frozen handoff package")
    lines.append("")
    lines.append("| Report | Target | Exit | Required checks passed |")
    lines.append("|---|---|---:|---|")
    lines.append(
        f"| [reports/handoff-fixture.json](reports/handoff-fixture.json) | `{handoff['target']}` "
        f"| {handoff['exit_code']} | {_required_summary(handoff['checks'])} |"
    )
    lines.append("")

    lines.append("## Reference consumers")
    lines.append("")
    header = "| Consumer | Framework | " + " | ".join(CHECK_ORDER) + " | Required |"
    rule = "|---|---|" + "---|" * (len(CHECK_ORDER) + 1)
    lines.append(header)
    lines.append(rule)
    for name, framework in CONSUMER_REPORTS:
        report = json.loads((REPORTS_DIR / f"{name}.json").read_text(encoding="utf-8"))
        by_name = {check["name"]: check for check in report["checks"]}
        cells = " | ".join(_status_cell(by_name[check]["status"]) for check in CHECK_ORDER)
        lines.append(
            f"| [{name}](reports/{name}.json) | {framework} | {cells} | {_required_summary(report['checks'])} |"
        )
    lines.append("")
    lines.append(
        "Browser layers report `unavailable` because interactive browser tooling is not wired "
        "into this release; the interactive consumers still pass every automatable required "
        "layer, and the missing layer stays visible instead of being dropped."
    )
    lines.append("")

    index = json.loads(RUNS_INDEX_PATH.read_text(encoding="utf-8"))
    runs = index.get("runs", [])
    agents = sorted({run["agent"] for run in runs})
    lines.append("## Cross-Agent run records")
    lines.append("")
    lines.append(f"Recorded runs: {len(runs)}. Distinct Coding Agent products: {len(agents)}.")
    lines.append("")
    if len(agents) >= REQUIRED_AGENTS_FOR_CLAIM:
        lines.append('Status of the "validated across Coding Agents" claim: **met by the checked-in records**.')
    else:
        lines.append(
            'Status of the "validated across Coding Agents" claim: **PENDING** — the threshold is '
            f"{REQUIRED_AGENTS_FOR_CLAIM} distinct Coding Agent products completing the frozen task "
            "(plan section 13.4). Only the framework-consumption evidence above is claimed; no run "
            "is fabricated to close the gap. Recording procedure: [runs/README.md](runs/README.md)."
        )
    lines.append("")

    rubric = json.loads(RUBRIC_PATH.read_text(encoding="utf-8"))
    lines.append("## Conformance rubric")
    lines.append("")
    lines.append("| Category | Weight | Objective evidence |")
    lines.append("|---|---:|---|")
    for category in rubric["categories"]:
        lines.append(f"| {category['id']} | {category['weight']} | {category['evidence']} |")
    lines.append("")
    lines.append(rubric["human_notes"]["role"] + " Score effect: "
                 f"{rubric['human_notes']['score_effect']}.")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    markdown = build_markdown()
    OUTPUT_PATH.write_text(markdown, encoding="utf-8")
    print(f"conformance table: {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
