import assert from 'node:assert/strict';
import {resolveEditPlan} from '../beatscope/runtime/edit-plan.js';
import {makePlan} from '../beatscope/web/mv-plan.mjs';
const rhythm={source:{duration:8,sha256:'test'},onsets:[{id:20,time:1,strength:.9},{id:30,time:2,strength:.8},{id:40,time:3,strength:.9}],patterns:{segments:[{id:'a',family:'A',start_time:0,end_time:4},{id:'b',family:'B',start_time:4,end_time:8}]}};
const plan={schema:'beatscope-edit-plan-1',source_sha256:'test',duration:8,boundaries:[{id:'s:custom',time:5}],cues:[{id:'o:0',deleted:true},{id:'o:1',time:2.123},{id:'u:added',time:2.15}]};
const original=structuredClone(rhythm);
const {stages,cues}=resolveEditPlan(rhythm,plan);
assert.deepEqual(stages.map(s=>[s.start,s.end]),[[0,5],[5,8]]);
assert.deepEqual(cues.map(c=>c.time),[2.123,2.15,3]);
assert.equal(cues[0].sourceTime,2);
const response={available:true,events:rhythm.onsets.map(o=>({...o,response_relevance:.9}))};
const compiled=makePlan(rhythm,response,1,plan);
assert.deepEqual(compiled.shots.map(s=>s.start),[0,2.123,2.15,3,5]);
assert.equal(compiled.shots.at(-1).stageStart,5);
assert.equal(compiled.details[0].source_time,2);
assert.deepEqual(rhythm,original);
assert.throws(()=>resolveEditPlan(rhythm,{...plan,source_sha256:'other'}));
assert.throws(()=>resolveEditPlan(rhythm,{...plan,boundaries:[{id:'a',time:3},{id:'b',time:2}]}));
console.log('Edit plan: stage replacement, muted/moved/added cues, dense manual cuts and immutable facts passed');
