/**
 * TypeScript mirror of `beatscope/direction.py`.
 *
 * The Python module is the normative implementation; this file re-states the
 * two halves the browser needs — validation with stable `direction/...`
 * codes, and canonical JSON bytes — so the editor can round-trip documents
 * against the server without a round trip to Python. Byte equality between
 * the two implementations is pinned by tests/test_direction_contract.js
 * against tests/fixtures/direction/contract-corpus.json (generated by
 * tests/fixtures/direction/generate_contract_corpus.py).
 *
 * Canonical bytes: compact JSON, object keys sorted by code point, numbers
 * formatted at exactly six fractional decimals with trailing zeros stripped
 * (integral values lose the dot, minus zero becomes 0), strings escaped
 * like `json.dumps(..., ensure_ascii=False)`. Direction values are authored
 * at <= 6 fractional decimals; inputs with finer precision are rounded by
 * this formatter, and the server stores the rounded canonical form.
 *
 * This module must stay free of value imports so the dedicated tsconfig can
 * emit it as a self-contained ES module for the Node contract tests.
 */
import type {
  DirectionDocument,
  DirectionLayer,
  DirectionScene,
  ResponseChain,
  SceneAnchor,
} from './types';

export const DIRECTION_SCHEMA = 'beatscope-direction-1';

export interface ValidationResult {
  errors: string[];
  notices: string[];
}

const TRANSITIONS = ['cut', 'dissolve', 'directional-wipe', 'split-reveal', 'hold-through'];
const LAYER_KINDS = ['editorial-typography', 'graphic-field', 'media-slice'];
const DRIVER_KINDS = [
  'ranked_onsets',
  'beat_phase',
  'downbeat_impulse',
  'energy_envelope',
  'structure_boundary',
  'scene_phase',
  'transition_phase',
];
const MOTION_KINDS = [
  'scale_pulse',
  'radial_expand',
  'translate_recoil',
  'translate_drift',
  'rotate_recoil',
  'crop_reveal',
  'strip_offset',
  'opacity_lift',
  'opacity_fade',
  'blur_focus',
  'invert_palette',
];
const BLEND_MODES = ['normal', 'multiply', 'screen', 'difference', 'overlay'];
const TRANSITION_REPR = "['cut', 'dissolve', 'directional-wipe', 'hold-through', 'split-reveal']";

const TIME_EPSILON = 1e-3;

function isInt(value: unknown): value is number {
  return typeof value === 'number' && Number.isInteger(value);
}

function isFiniteNumber(value: unknown): value is number {
  return typeof value === 'number' && Number.isFinite(value);
}

function isSlug(value: unknown): boolean {
  return typeof value === 'string' && value.length > 0 && /^[0-9a-zA-Z][0-9a-zA-Z-]*$/.test(value) && value === value.toLowerCase();
}

function isSceneId(value: unknown): boolean {
  return typeof value === 'string' && value.startsWith('scene-') && value.length > 6 && isSlug(value.slice(6));
}

function hexOk(value: unknown, length: number): boolean {
  return typeof value === 'string' && value.length === length && /^[0-9a-f]*$/.test(value);
}

/** Six fractional decimals, trailing zeros stripped, -0 -> 0 (mirrors `_canonical_number`). */
export function canonicalNumber(x: number): string {
  if (!Number.isFinite(x)) throw new Error(`direction document contains a non-finite number: ${x}`);
  let text = x.toFixed(6);
  if (text.includes('.')) text = text.replace(/0+$/, '').replace(/\.$/, '');
  if (text === '-0' || text === '') text = '0';
  return text;
}

function walkNonfinite(value: unknown, path: string, errors: string[]): void {
  if (typeof value === 'number' && !Number.isFinite(value)) {
    errors.push(`direction/non-finite: ${path} must be a finite number`);
  } else if (Array.isArray(value)) {
    value.forEach((item, index) => walkNonfinite(item, `${path}[${index}]`, errors));
  } else if (value !== null && typeof value === 'object') {
    for (const [key, item] of Object.entries(value)) walkNonfinite(item, `${path}.${key}`, errors);
  }
}

function validateLayer(
  layer: DirectionLayer,
  label: string,
  errors: string[],
  notices: string[],
  assetIds?: Set<string>,
): void {
  if (!isSlug(layer.id)) {
    errors.push(`direction/layer-id: ${label}.id must be a non-empty lowercase slug`);
  }
  if (typeof layer.label !== 'string' || layer.label.length === 0) {
    errors.push(`direction/layer-label: ${label}.label must be a non-empty string`);
  }
  if (typeof layer.visible !== 'boolean' || typeof layer.locked !== 'boolean') {
    errors.push(`direction/layer-flags: ${label}.visible/.locked must be booleans`);
  }
  if (!isFiniteNumber(layer.opacity) || layer.opacity < 0 || layer.opacity > 1) {
    errors.push(`direction/layer-opacity: ${label}.opacity must be within 0..1`);
  }
  if (typeof layer.blend !== 'string') {
    errors.push(`direction/layer-blend: ${label}.blend must be a string`);
  } else if (!BLEND_MODES.includes(layer.blend)) {
    notices.push(`direction/layer-blend-unknown: ${label}.blend '${layer.blend}' is not in the core set; preserved as authored`);
  }
  if (typeof layer.kind !== 'string' || layer.kind.length === 0) {
    errors.push(`direction/layer-kind: ${label}.kind must be a non-empty string`);
  } else if (!LAYER_KINDS.includes(layer.kind)) {
    notices.push(`direction/layer-kind-unknown: ${label}.kind '${layer.kind}' is not registered; preserved as authored`);
  }
  const t = layer.transform;
  if (t === null || typeof t !== 'object') {
    errors.push(`direction/layer-transform: ${label}.transform must be an object`);
  } else {
    const { x, y, w, h, rotation, crop } = t;
    if (![x, y, w, h].every(isFiniteNumber)) {
      errors.push(`direction/layer-transform: ${label}.transform.x/.y/.w/.h must be finite numbers`);
    } else {
      if (x < 0 || x > 1 || y < 0 || y > 1) {
        errors.push(`direction/layer-transform: ${label}.transform.x/.y must be normalized 0..1`);
      }
      if (w <= 0 || h <= 0) {
        errors.push(`direction/layer-transform: ${label}.transform.w/.h must be positive`);
      }
    }
    if (!isFiniteNumber(rotation)) {
      errors.push(`direction/layer-transform: ${label}.transform.rotation must be finite`);
    }
    if (crop !== undefined) {
      if (
        crop === null || typeof crop !== 'object'
        || ![crop.left, crop.top, crop.right, crop.bottom].every(isFiniteNumber)
        || ![crop.left, crop.top, crop.right, crop.bottom].every((v) => v >= 0 && v <= 1)
      ) {
        errors.push(`direction/layer-transform: ${label}.transform.crop must carry left/top/right/bottom within 0..1`);
      }
    }
  }
  if (assetIds) {
    const src = (layer.props as Record<string, unknown> | undefined)?.src;
    if (typeof src === 'string' && src.startsWith('asset:') && !assetIds.has(src.slice('asset:'.length))) {
      errors.push(`direction/asset-missing: ${label}.props.src references '${src}' which is not in the project manifest`);
    }
  }
}

function validateDriver(driver: unknown, label: string, errors: string[], notices: string[]): void {
  if (driver === null || typeof driver !== 'object' || typeof (driver as Record<string, unknown>).kind !== 'string') {
    errors.push(`direction/driver: ${label}.driver must be an object with a kind`);
    return;
  }
  const d = driver as Record<string, any>;
  if (!DRIVER_KINDS.includes(d.kind)) {
    notices.push(`direction/driver-unknown: ${label}.driver.kind '${d.kind}' is not registered; preserved as authored`);
    return;
  }
  if (d.kind === 'ranked_onsets') {
    if ((d.band !== 'low' && d.band !== 'mid' && d.band !== 'high') || (d.tier !== 'primary' && d.tier !== 'secondary')) {
      errors.push(`direction/driver: ${label}.driver band/tier are out of range`);
    }
    if (!isInt(d.max_events_per_bar) || d.max_events_per_bar < 1) {
      errors.push(`direction/driver: ${label}.driver.max_events_per_bar must be a positive integer`);
    }
    if (!isFiniteNumber(d.refractory_beats) || d.refractory_beats < 0) {
      errors.push(`direction/driver: ${label}.driver.refractory_beats must be a non-negative number`);
    }
  } else if (d.kind === 'beat_phase') {
    if (d.subdivision !== 1 && d.subdivision !== 2 && d.subdivision !== 4) {
      errors.push(`direction/driver: ${label}.driver.subdivision must be 1, 2 or 4`);
    }
  } else if (d.kind === 'energy_envelope') {
    if (d.band !== 'low' && d.band !== 'mid' && d.band !== 'high') {
      errors.push(`direction/driver: ${label}.driver.band must be low, mid or high`);
    }
  }
  // downbeat_impulse / structure_boundary / scene_phase / transition_phase
  // carry no extra fields; availability is decided at compile time.
}

function validateMotion(motion: unknown, label: string, errors: string[], notices: string[]): void {
  if (motion === null || typeof motion !== 'object' || typeof (motion as Record<string, unknown>).kind !== 'string') {
    errors.push(`direction/motion: ${label}.motion must be an object with a kind`);
    return;
  }
  const m = motion as Record<string, any>;
  if (!MOTION_KINDS.includes(m.kind)) {
    notices.push(`direction/motion-unknown: ${label}.motion.kind '${m.kind}' is not registered; preserved as authored`);
    return;
  }
  for (const field of ['attack_seconds', 'release_seconds'] as const) {
    if (!isFiniteNumber(m[field]) || m[field] < 0) {
      errors.push(`direction/motion: ${label}.motion.${field} must be a non-negative number`);
    }
  }
  if (!isFiniteNumber(m.amount)) {
    errors.push(`direction/motion: ${label}.motion.amount must be a finite number`);
  }
  if (m.kind === 'translate_recoil' || m.kind === 'translate_drift') {
    if (!Array.isArray(m.axis) || m.axis.length !== 2 || !m.axis.every(isFiniteNumber)) {
      errors.push(`direction/motion: ${label}.motion.axis must be a pair of finite numbers`);
    }
  }
}

function anchorError(scene: DirectionScene, label: string, errors: string[]): SceneAnchor | null {
  const anchor = scene.anchor as SceneAnchor | undefined;
  if (anchor === null || typeof anchor !== 'object' || (anchor.kind !== 'bars' && anchor.kind !== 'time')) {
    errors.push(`direction/anchor: ${label}.anchor.kind must be 'bars' or 'time'`);
    return null;
  }
  if (anchor.kind === 'bars') {
    if (!isInt(anchor.start_bar) || anchor.start_bar < 1 || !isInt(anchor.end_bar) || anchor.end_bar < 1 || anchor.end_bar <= anchor.start_bar) {
      errors.push(`direction/anchor: ${label}.anchor bars must be integers with start_bar < end_bar (1-based, exclusive end)`);
      return null;
    }
  } else if (!isFiniteNumber(anchor.start_seconds) || anchor.start_seconds < 0 || !isFiniteNumber(anchor.end_seconds) || anchor.end_seconds <= anchor.start_seconds) {
    errors.push(`direction/anchor: ${label}.anchor seconds must be finite with start_seconds < end_seconds`);
    return null;
  }
  return anchor;
}

function sceneTimeOk(scene: DirectionScene, label: string, errors: string[]): [number, number] | null {
  const { start_time: start, end_time: end } = scene;
  if (!isFiniteNumber(start) || start < 0 || !isFiniteNumber(end) || end <= start) {
    errors.push(`direction/scene-times: ${label} start_time/end_time must be finite with start_time < end_time`);
    return null;
  }
  return [start, end];
}

export function validateDirection(doc: unknown, options: { assetIds?: Set<string> } = {}): ValidationResult {
  const errors: string[] = [];
  const notices: string[] = [];
  if (doc === null || typeof doc !== 'object' || Array.isArray(doc)) {
    return { errors: ['direction/schema: document must be an object'], notices };
  }
  const d = doc as Record<string, any>;
  walkNonfinite(d, 'doc', errors);

  if (d.schema !== DIRECTION_SCHEMA) {
    errors.push(`direction/schema-version: schema must be '${DIRECTION_SCHEMA}'`);
  }
  if (typeof d.version !== 'string' || d.version.length === 0) {
    errors.push('direction/version: version must be a non-empty string');
  }
  if (!hexOk(d.project_id, 12)) {
    errors.push('direction/project-id: project_id must be 12 lowercase hex characters');
  }
  if (typeof d.project_title !== 'string' || d.project_title.length === 0) {
    errors.push('direction/title: project_title must be a non-empty string');
  }
  if (!hexOk(d.source_rhythm_sha256, 64)) {
    errors.push('direction/source-sha: source_rhythm_sha256 must be 64 hex characters');
  }

  const composition = d.composition as Record<string, unknown> | undefined;
  if (composition === null || typeof composition !== 'object' || Array.isArray(composition)) {
    errors.push('direction/composition: composition must be an object');
  } else {
    const ratio = composition.primary_ratio;
    if (ratio !== '16:9' && ratio !== '9:16' && ratio !== '1:1') {
      errors.push("direction/ratio: primary_ratio must be '16:9', '9:16' or '1:1'");
    } else {
      const [width, height] =
        ratio === '16:9' ? [1920, 1080] : ratio === '9:16' ? [1080, 1920] : [1080, 1080];
      if (composition.width !== width || composition.height !== height) {
        errors.push(`direction/composition: ${ratio} requires ${width}x${height}`);
      }
    }
    const background = composition.background;
    if (typeof background !== 'string' || !background.startsWith('#') || background.length !== 7) {
      errors.push('direction/composition: background must be a #rrggbb string');
    }
  }

  for (const [field, array] of [['theme', false], ['assets', true], ['transitions', true], ['diagnostics', false]] as const) {
    const value = d[field];
    const valid = array ? Array.isArray(value) : value !== null && typeof value === 'object' && !Array.isArray(value);
    if (!valid) errors.push(`direction/${field}: ${field} must be a ${array ? 'list' : 'dict'}`);
  }

  const scenes = d.scenes;
  if (!Array.isArray(scenes) || scenes.length === 0) {
    errors.push('direction/scenes: scenes must be a non-empty list');
    return { errors, notices };
  }

  const sceneIds = new Set<string>();
  let previousEndTime: number | null = null;
  let previousEndBar: number | null = null;
  scenes.forEach((scene: DirectionScene, position: number) => {
    const label = `scenes[${position}]`;
    if (scene === null || typeof scene !== 'object' || Array.isArray(scene)) {
      errors.push(`direction/scenes: ${label} must be an object`);
      return;
    }
    if (!isSceneId(scene.id)) {
      errors.push(`direction/scene-id: ${label}.id must match scene-<lowercase-slug>`);
    } else if (sceneIds.has(scene.id)) {
      errors.push(`direction/scene-duplicate: ${label}.id '${scene.id}' is duplicated`);
    } else {
      sceneIds.add(scene.id);
    }
    if (typeof scene.title !== 'string' || scene.title.length === 0) {
      errors.push(`direction/scene-title: ${label}.title must be a non-empty string`);
    }
    if (typeof scene.family !== 'string') {
      errors.push(`direction/scene-family: ${label}.family must be a string`);
    }
    if (!TRANSITIONS.includes(scene.transition_out)) {
      errors.push(`direction/scene-transition: ${label}.transition_out must be one of ${TRANSITION_REPR}`);
    }

    const span = sceneTimeOk(scene, label, errors);
    const anchor = anchorError(scene, label, errors);
    if (anchor !== null && anchor.kind === 'bars') {
      if (previousEndBar !== null) {
        if (anchor.start_bar !== previousEndBar) {
          errors.push(
            `direction/scene-overlap: ${label} starts at bar ${anchor.start_bar} `
            + `while the previous scene ends at bar ${previousEndBar}`,
          );
        }
      }
      previousEndBar = anchor.end_bar;
    }
    if (span !== null) {
      if (previousEndTime !== null && Math.abs(span[0] - previousEndTime) > TIME_EPSILON) {
        errors.push(
          `direction/scene-continuity: ${label} starts at ${canonicalNumber(span[0])} `
          + `while the previous scene ends at ${canonicalNumber(previousEndTime)}`,
        );
      }
      previousEndTime = span[1];
    }

    const layers = Array.isArray(scene.layers) ? scene.layers : [];
    if (!Array.isArray(scene.layers)) {
      errors.push(`direction/scenes: ${label}.layers must be a list`);
    }
    const layerIds = new Set<string>();
    layers.forEach((layer: DirectionLayer, lpos: number) => {
      const llabel = `${label}.layers[${lpos}]`;
      if (layer === null || typeof layer !== 'object' || Array.isArray(layer)) {
        errors.push(`direction/scenes: ${llabel} must be an object`);
        return;
      }
      validateLayer(layer, llabel, errors, notices, options.assetIds);
      if (typeof layer.id === 'string') {
        if (layerIds.has(layer.id)) {
          errors.push(`direction/layer-duplicate: ${llabel}.id '${layer.id}' is duplicated`);
        }
        layerIds.add(layer.id);
      }
    });

    const responses = Array.isArray(scene.responses) ? scene.responses : [];
    if (!Array.isArray(scene.responses)) {
      errors.push(`direction/scenes: ${label}.responses must be a list`);
    }
    const responseIds = new Set<string>();
    responses.forEach((response: ResponseChain, rpos: number) => {
      const rlabel = `${label}.responses[${rpos}]`;
      if (response === null || typeof response !== 'object' || Array.isArray(response)) {
        errors.push(`direction/scenes: ${rlabel} must be an object`);
        return;
      }
      if (typeof response.id !== 'string' || response.id.length === 0) {
        errors.push(`direction/response-id: ${rlabel}.id must be a non-empty string`);
      } else if (responseIds.has(response.id)) {
        errors.push(`direction/response-duplicate: ${rlabel}.id '${response.id}' is duplicated`);
      } else {
        responseIds.add(response.id);
      }
      if (typeof response.label !== 'string' || response.label.length === 0) {
        errors.push(`direction/response-label: ${rlabel}.label must be a non-empty string`);
      }
      if (!layerIds.has(response.target_layer_id)) {
        errors.push(`direction/response-layer: ${rlabel}.target_layer_id '${response.target_layer_id}' does not exist in this scene`);
      }
      if (response.unavailable_reason !== undefined && typeof response.unavailable_reason !== 'string') {
        errors.push(`direction/response-unavailable: ${rlabel}.unavailable_reason must be a string when present`);
      }
      validateDriver(response.driver, rlabel, errors, notices);
      validateMotion(response.motion, rlabel, errors, notices);
    });
  });

  return { errors, notices };
}

/** Python `sorted()` order: by Unicode code point, not UTF-16 units. */
function compareCodePoints(a: string, b: string): number {
  let i = 0;
  let j = 0;
  while (i < a.length && j < b.length) {
    const ca = a.codePointAt(i) as number;
    const cb = b.codePointAt(j) as number;
    if (ca !== cb) return ca < cb ? -1 : 1;
    i += ca > 0xffff ? 2 : 1;
    j += cb > 0xffff ? 2 : 1;
  }
  if (i >= a.length && j >= b.length) return 0;
  return i >= a.length ? -1 : 1;
}

export function canonicalJson(value: unknown, out: string[]): void {
  if (value === null) {
    out.push('null');
  } else if (value === true) {
    out.push('true');
  } else if (value === false) {
    out.push('false');
  } else if (typeof value === 'number') {
    if (Number.isInteger(value) && Math.abs(value) < 1e15) out.push(String(value));
    else out.push(canonicalNumber(value));
  } else if (typeof value === 'string') {
    out.push(JSON.stringify(value));
  } else if (Array.isArray(value)) {
    out.push('[');
    value.forEach((item, index) => {
      if (index) out.push(',');
      canonicalJson(item, out);
    });
    out.push(']');
  } else if (value !== null && typeof value === 'object') {
    const record = value as Record<string, unknown>;
    out.push('{');
    // JSON.stringify semantics: explicit `undefined` members are omitted, so
    // in-memory docs carrying e.g. `crop: undefined` canonicalize exactly
    // like the Python dict (which has no undefined at all).
    const keys = Object.keys(record)
      .filter((key) => record[key] !== undefined)
      .sort(compareCodePoints);
    keys.forEach((key, index) => {
      if (index) out.push(',');
      out.push(JSON.stringify(key));
      out.push(':');
      canonicalJson(record[key], out);
    });
    out.push('}');
  } else {
    throw new TypeError(`direction document contains unsupported value: ${typeof value}`);
  }
}

/** Canonical JSON string; throws when the document does not validate. */
export function canonicalDirectionString(doc: DirectionDocument): string {
  const { errors } = validateDirection(doc);
  if (errors.length > 0) {
    throw new Error(`cannot canonicalize an invalid direction document: ${errors.join('; ')}`);
  }
  const out: string[] = [];
  canonicalJson(doc, out);
  return out.join('');
}

/** Canonical UTF-8 bytes (byte-identical to `canonical_direction_bytes`). */
export function canonicalDirectionBytes(doc: DirectionDocument): Uint8Array<ArrayBuffer> {
  // TextEncoder types its buffer as ArrayBufferLike; encode() always
  // allocates a plain ArrayBuffer, so the cast is sound.
  return new TextEncoder().encode(canonicalDirectionString(doc)) as Uint8Array<ArrayBuffer>;
}
